# -*- coding: utf-8 -*-
"""drug_fine_Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bVg9gMmtqBG2QKEhQ0l1gF1it92MhC7
"""

# from google.colab import userdata
# OPENAI_API_KEY=userdata.get('OPEN_AI_TOKEN')

import os
os.environ["OPENAI_API_KEY"] = "Your ApI kEY"
OPENAI_API_KEY=os.environ['OPENAI_API_KEY' ]

from openai import OpenAI # type: ignore

client = OpenAI()

client.files.create(file=open("drug_malady_data_transformed.jsonl","rb"),purpose='fine-tune')

file_id='file-rBwcNhSCe7Xk7ugC7JTWpY0V'

files = client.files.list()

for file in files.data:
  print(file)

for file in files.data:
  if file.filename == 'drug_malady_data_transformed.jsonl':
    training_file_id = file.id

client.fine_tuning.jobs.create(
    training_file=training_file_id,
    model="gpt-3.5-turbo"
)

jobs=client.fine_tuning.jobs.list()

for job in jobs:
  print(job)

client.fine_tuning.jobs.retrieve('ftjob-y0Ezh1mEfMETZ0QC5t8c3Yoo')

# Configure the model ID. Change this to your model ID.
drug_fine_tune_llm='ft:gpt-3.5-turbo-0125:personal::AVp6l4b9'


# Let's use a drug from each class
drugs = [
    "A CN Gel(Topical) 20gmA CN Soap 75gm",  # Class 0
    "Addnok Tablet 20'S",                    # Class 1
    "ABICET M Tablet 10's",                  # Class 2
]

# Returns a drug class for each drug
for drug_name in drugs:
    prompt = "Drug: {}\nMalady:".format(drug_name)
    print(prompt)
    response = client.chat.completions.create(
        model=drug_fine_tune_llm,
         messages=[{"role": "system", "content": "You are a medical assistant specializing in drug and malady classification. You help classify drugs and match them with possible ailments."},
              {"role": "user", "content": prompt}],
    )
    # Print the generated text
    drug_class = response.choices[0].message.content.strip()
    # The result should be 0, 1, and 2
    print('Class:',drug_class)

